export const userConstant = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGIN_ERROR: 'USERS_LOGIN_ERROR',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    REGISTER_ERROR: 'USERS_REGISTER_ERROR',
    SET_REQUEST_STATUS: 'REQUEST_STATUS',

    LOGOUT: 'USERS_LOGOUT',

    SET_TOKEN: 'SET_TOKEN',

};
